# Generated by Django 5.2.4 on 2025-11-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_instractor_student_exam_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='title',
            new_name='exam_title',
        ),
    ]
